Use `await` in the `next/headers` to prevent errors
We need to use `await` on the `next/headers` since `headers()` returns a promise. Directly accessing it shows an error in the console.

```bash
Error: In route / a header property was accessed directly with `headers().get('cookie')`. `headers()` should be awaited before using its value. Learn more: https://nextjs.org/docs/messages/sync-dynamic-apis
```